server/djangoapp/urls.py
'''urls definition'''
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'

urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    path(route='', view=views.get_dealerships, name='index'),

    # path for about view
     path(route='about/', view=views.about, name='about'),

    # path for contact us view
    path(route='contact/', view=views.contact, name='contact'),

    # path for registration
    path(route='registration/', view=views.registration_request, name='registration'),

    # path for login
    path(route='login/', view=views.login_request, name='login'),

    # path for logout
    path(route='logout/', view=views.logout_request, name='logout'),

    # path for dealer reviews view
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path(route='dealer/<int:dealer_id>/add_review', view=views.add_review, name='add_review'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

# <HINT> Create a Car Make model `class CarMake(models.Model)`:
# - Name
# - Description
# - Any other fields you would like to include in car make model
# - __str__ method to print a car make object
class CarMake(models.Model):
    '''Create a Car Make model'''
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=320)
    
    def __str__(self) -> str:
        return self.name + ""


# <HINT> Create a Car Model model `class CarModel(models.Model):`:
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
# - Name
# - Dealer id, used to refer a dealer created in cloudant database
# - Type (CharField with a choices argument to provide limited choices such as Sedan, SUV, WAGON, etc.)
# - Year (DateField)
# - Any other fields you would like to include in car model
# - __str__ method to print a car make object
class CarModel(models.Model):
    '''Create a Car Model model'''
    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    type_c = models.CharField(max_length=10, choices=(('Sedan', 'Sedan',), ('SUV', 'SUV'), ('HATCHBACK', 'HATCHBACK'),('WAGON', 'WAGON')))
    dealer_id = models.IntegerField()
    year = models.DateField() 
    def __str__(self) -> str:
        return self.name + ""


# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:
    '''Create a plain Python class CarDealer'''
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip
    def __str__(self):
        return "Dealer name: " + self.full_name


# <HINT> Create a plain Python class `DealerReview` to hold review data
class DealerReview:
    '''Create a plain Python class DealerReview'''
    def __init__(self, dealership, name, purchase, review, purchase_date,
     car_make, car_model, car_year, sentiment, id):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment
        self.id = id

server/djangoapp/views.py
'''Views'''
import logging
from datetime import datetime
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf, post_request
from .models import CarModel


# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
# def about(request):
# ...
def about(request):
    '''Creates an `about` view to render a static about page'''
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
#def contact(request):
def contact(request):
    '''Creates a `contact` view to return a static contact page'''
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)


# This view and this page is not part of the exercise,
# I just thought it would be an effective way to get around with errors
# without blocking the execution of the code.
#=======================================================================
# Create a `error` view to return a static contact page
#def contact(request):
def error(request):
    '''Creates a `error` view to return a static error page'''
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/error.html', context)
#======================================================================


# Create a `login_request` view to handle sign in request
# def login_request(request):
# ...
def login_request(request):
    '''Creates a `login_request` view to handle sign in request'''
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
    if username == "" or password == "": # In case the fields are empty
        context['error'] =  ("Forgot your login details? No problem! "
        "Get in touch with us, and "
        "we will be happy to help you. "
        "You will be now directed to our contacts page.")
        return render(request, 'djangoapp/contact.html', context)
    elif user is not None:    
        login(request, user)
        return render(request, 'djangoapp/index.html', context)
    else: # In case the credentials are wrong
        context['error'] =  ("INCORRECT LOGIN DETAILS!!! But don t worry! "
        "You will be now directed to our error page. "
        "You can try again, there is no limit to the number of attempts! "
        "Use our contact page if you have any questions.")
        return render(request, 'djangoapp/error.html', context)


# Create a `logout_request` view to handle sign out request
# def logout_request(request):
# ...
def logout_request(request):
    '''Creates a `logout_request` view to handle sign out request'''
    context = {}
    print("Log out the user `{}`".format(request.user.username))
    logout(request)
    return render(request, 'djangoapp/index.html', context)


# Create a `registration_request` view to handle sign up request
# def registration_request(request):
# ...
def registration_request(request):
    '''Creates a `registration_request` view to handle sign up request'''
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except():
            logger.debug("{} is new user".format(username))
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name,
             last_name=last_name, password=password)
            login(request, user)
            return render(request, 'djangoapp/index.html', context)
        else:
            return render(request, 'djangoapp/index.html', context)
    else:
        return render(request, 'djangoapp/index.html', context)


# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    '''Update the `get_dealerships` view to render the index page with a list of dealerships'''
    if request.method == "GET":
        url = "https://eu-gb.functions.appdomain.cloud/api/v1/web/083e1099-73a9-4b54-b7a4-454021498f80/api/dealerships.json"
        # Get dealers from the URL
        try:
            dealerships = get_dealers_from_cf(url)
            context = {
                "dealerships": dealerships,
            }
            return render(request, 'djangoapp/index.html', context)
        except Exception as e:
            # If an error occurs, redirect to an error page
            print(e)  # Print the error to the console
            return render(request, 'djangoapp/error.html')


# Create a `get_dealer_details` view to render the reviews of a dealer
# def get_dealer_details(request, dealer_id):
def get_dealer_details(request, dealer_id):
    '''Create a `get_dealer_details` view to render the reviews of a dealer'''
    if request.method == "GET":
        url_r = f"https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/a9220b6d6b26f1eb3b657a98770b743616f7d4cd223b89cd1ca4e88ab49bdb92/api/review?dealerId={dealer_id}"
        url_ds = f"https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/a9220b6d6b26f1eb3b657a98770b743616f7d4cd223b89cd1ca4e88ab49bdb92/api/dealership?dealerId={dealer_id}"
        # Get dealers from the URL
        try:
            context = {
               "dealer": get_dealers_from_cf(url_ds)[0],
               "reviews": get_dealer_reviews_from_cf(url_r, dealer_id),
            }
            return render(request, 'djangoapp/dealer_details.html', context)
        except Exception as e:
            # If an error occurs, redirect to an error page
            print(e)  # Print the error to the console
            return render(request, 'djangoapp/error.html')


# Create a `add_review` view to submit a review
# def add_review(request, dealer_id):
def add_review(request, dealer_id):
    '''Create a `add_review` view to submit a review'''
    if request.method == "GET":
        url = f"https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/a9220b6d6b26f1eb3b657a98770b743616f7d4cd223b89cd1ca4e88ab49bdb92/api/dealership?dealerId={dealer_id}"
        # Get dealers from the URL
        try:
            context = {
                "cars": CarModel.objects.all(),
                "dealer": get_dealers_from_cf(url)[0],
            }
            print(context)
            return render(request, 'djangoapp/add_review.html', context)
        except Exception as e:
            # If an error occurs, redirect to an error page
            print(e)  # Print the error to the console
            return render(request, 'djangoapp/error.html')
    if request.method == "POST":
        form = request.POST
        review = {
            "name": f"{request.user.first_name} {request.user.last_name}",
            "dealership": dealer_id,
            "review": form["content"],
            "purchase": form.get("purchasecheck"),
            }
        if form.get("purchasecheck"):
            review["purchasedate"] = datetime.strptime(form.get("purchasedate"), "%m/%d/%Y").isoformat()
            car = CarModel.objects.get(pk=form["car"])
            review["car_make"] = car.car_make.name
            review["car_model"] = car.name
            review["car_year"]= car.year.strftime("%Y")
        json_payload = {"review": review}
        URL = 'https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/a9220b6d6b26f1eb3b657a98770b743616f7d4cd223b89cd1ca4e88ab49bdb92/api/review'
        post_request(URL, json_payload, dealerId=dealer_id)
    return redirect("djangoapp:dealer_details", dealer_id=dealer_id)

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'djangoapp/dealer.css' %}">
        <meta charset="UTF-8">
        <title>Best Car Dealer</title>
    </head>
    
    <body>  
        
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="btn btn-primary" href="{% url 'djangoapp:index' %}">Home Page</a>
                    <a class="btn btn-primary" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
    
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Username" name="username">
                                <input type="password" class="form-control" placeholder="Password" name="psw">
                                <button class="btn btn-primary" type="submit">Login</button>
                                <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                            </div>
                        </form>
                    </li>
                    {% endif %}
                </ul>
    
            </div>
        </nav>

        <div class="tille">
            <b class="mt-5 p text-left">
                <br><img height="60px" length="60px" src="/media/images/dealer.png">
                Best Car Dealer! <br><br>
            </b>
            <p>
                About Us Page. <br>
            </p>
            <hr>
        </div>

        <div class="card">
            <p class="mt-3 p text-left">
                <img height="190px" length="390px" src="/media/images/cardealer.png"class="card-img-left">
                <br><br><strong>Welcome to Best Cars dealership,</strong> home to the best cars in North America. <br> We sell domestic and imported cars at reasonable prices.<br>
            </p>
        </div>

        <footer>
            <p><br>Copyright © 2023 Best Car Dealer! All rights reserved.</p>
        </footer>

    </body>

</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'djangoapp/dealer.css' %}">
    <meta charset="UTF-8">
    <title>Best Car Dealer</title>
</head>

<body>

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="btn btn-primary" href="{% url 'djangoapp:index' %}">Home Page</a>
                <a class="btn btn-primary" href="{% url 'djangoapp:about' %}">About Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>

        </div>
    </nav>


    <div class="tille">
        <b class="mt-5 p text-left">
            <br><img height="60px" length="60px" src="/media/images/dealer.png">
             Best Car Dealer! <br><br>
        </b>
        <p>
            Contacts page. <br>
        </p>
        <hr>
    </div>

    <div class="card">
        <p class="mt-3 p text-left">
            <img height="90px" length="120px" src="/media/images/contact-us.png"class="card-img-left">
            <br><br>Contact information:
        </p>
        
        <div class="mt-4 p text-left">
            <p><b>Phone No:</b> 900 001 002</p>
            <p><b>Email:</b> info@bestcardealer.tld
                <a href="mailto:info@bestcardealer.tld"></a></p>
            <p><b>Web Page:</b><a herf="https://www.google.com/">bestcardealer.tld<br><br><br></a></p>
        </div>
    </div>

    <footer>
        <p><br>Copyright © 2023 Best Car Dealer! All rights reserved.</p>
    </footer>
    
</body>

{% if error %}
<script type="text/javascript">
  alert("{{ error }}");
</script>
{% endif %}

</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'djangoapp/dealer.css' %}">
</head>

<body>

    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="btn btn-primary" href="{% url 'djangoapp:index' %}">Home Page</a>
                <a class="btn btn-primary" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="btn btn-primary" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                    <a class="btn btn-link" href="add_review">Add review</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>

        </div>
    </nav>

    <!--Page title and text.-->
    <div class="tille">
        <b class="mt-5 p text-left">
            <br><img height="60px" length="60px" src="/media/images/dealer.png">
             Best Car Dealer! <br><br>
        </b>
        <p>
            Welcome to our comments page. <br>
        </p>    
        {% for review in reviews %}
        <p>If you contact us, please use this ID to identify the seller. <strong>ID No: {{review.id}}</strong> <br></p>
        <hr>
        {% endfor %} {% if reviews|length == 0 %} 
        <p> OOPS! </p>
        <hr>
        {% endif %}
    
    </div>

    <!-- Add reviews as cards -->
    <div class="card-columns">
        {% for review in reviews %}
        <div class="card text-dark bg-light mb-3 text-left">
            <div class="card-header">{{review.name}}</div>
            <img height="40px" length="40px" src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left">
            <div class="card-body">
                <h5 class="card-title">{{ review.car_make }}, {{ review.car_model }}</h5>
                <h5 class="card-title">{{ review.car_year }}</h5>
                <p class="card-text">{{ review.review }}</p>
            </div>
        </div>
        {% endfor %} {% if reviews|length == 0 %}   
        <div class="card">
            <p class="mt-3 p text-left">
                <img height="60px" length="60px" src="/media/images/error.png" class="card-img-left"> 
                <br><br>This dealership has no reviews to show.
            </p>
        </div>
        {% endif %}
    </div>
    
    <footer>
        <p><br>Copyright © 2023 Best Car Dealer! All rights reserved.</p>
    </footer>

</body>

</html>

server/djangoapp/templates/djangoapp/error.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'djangoapp/dealer.css' %}">
        <meta charset="UTF-8">
        <title>Best Car Dealer</title>
    </head>

    <body> 
           
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="btn btn-primary" href="{% url 'djangoapp:index' %}">Home Page</a>
                    <a class="btn btn-primary" href="{% url 'djangoapp:about' %}">About Us</a>
                    <a class="btn btn-primary" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
    
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                        <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Username" name="username">
                                <input type="password" class="form-control" placeholder="Password" name="psw">
                                <button class="btn btn-primary" type="submit">Login</button>
                                <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                            </div>
                        </form>
                    </li>
                    {% endif %}
                </ul>
    
            </div>
        </nav>

        <div class="tille">
            <b class="mt-5 p text-left">
                <br><br>OOPS!!! Something went very wrong...<br><br>
            </b>
            <p>
                This is an error page. I would be happier if she hadn't shown up!<br><br>
            </p>
        </div>

        <div class="card">
            <p class="mt-1 p text-left">
                <img height="200px" length="150px" src="/media/images/oops01.png"class="card-img-left">
                <br><br> Congratulations, you just found a bug!<br><br>
                This page may have appeared for the following reasons: <br><br>
                Did you enter the wrong login credentials? <br>
                If not, there is probably an error in accessing the database.<br>
                Please contact-us and let us know!<br><br>
                If you did enter the wrong login credentials, try again!<br>
                In case you forgot your credentials contact-us. 
            </p>
        </div>

        <footer>
            <p><br>Copyright © 2023 Best Car Dealer! All rights reserved.</p>
        </footer>
        
    </body>

    {% if error %}
    <script type="text/javascript">
    alert("{{ error }}");
    </script>
    {% endif %}

</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head >

    <body style="background-color: #d6d6d6;">

        <img height="120px" length="120px" src="/media/images/dealer.png">
        <div class="tille">
            <b class="mt-0 p text-left">
                Best Car Dealer!
            </b>
        </div>

    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">

        <div class="container-fluid">
            <div class="navbar-header" >
                <a class="btn btn-primary" href="{% url 'djangoapp:index' %}">
                    <img src="/media/images/synchronize.png" alt="Refresh" width="20" height="20"> Refresh</a>
                <a class="btn btn-primary" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="btn btn-primary" href="{% url 'djangoapp:contact' %}">Contact Us</a>
       
            </div>

            <ul class="nav navbar-nav navbar-right">
                
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}

            </ul>

        </div>

    </nav>

    <!--Add a dealer table here -->

    <div class="container">
        <table class="table" id="table" data-filter-control="true">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Dealer Name</th>
                        <th scope="col">City</th>
                        <th scope="col">Address</th>
                        <th scope="col">Zip</th>               
                        <th data-field="state" data-filter-control="select">State</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dealer in dealerships %}
                    <tr>
                        <td>{{dealer.id}}</td>
                        <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                        <td>{{dealer.city}}</td>
                        <td>{{dealer.address}}</td>
                        <td>{{dealer.zip}}</td>
                        <td>{{dealer.st}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>

    <footer style="background-color:rgb(61, 114, 228); height:50px; position: fixed; bottom: 0; width: 100%;">
        <p style="text-align:center; color:white; font-size:12px;"><br>
            Copyright © 2023 Best Car Dealer! All rights reserved.</p>
    </footer>
    
    </body>

      <script>
        $(function() {
            $('#table').bootstrapTable()
        })
      </script>
    
    </html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'djangoapp/dealer.css' %}">
</head>

    <body>

        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="btn btn-primary" href="{% url 'djangoapp:index' %}">Home Page</a>
                </div>
            </div>
        </nav>

    <!--Add a registration form here -->

    <form action="{% url 'djangoapp:registration' %}" method="POST">
        <div class="container lead mt-5 text-left">
            <h1>Sign Up</h1>
            <hr>
            <div class="card-columns-vertical">
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required>
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required>
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required>
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required>
            </div>
            <div>
                {% csrf_token %}
                <button class="btn btn-primary mt-3" type="submit">Sign Up</button>
            </div>
        </div>
    </form>

    <footer>
        <p><br>Copyright © 2023 Best Car Dealer! All rights reserved.</p>
    </footer>

    </body>

</html>